name: PowerBI_Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-powerbi:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Power BI modules
        shell: pwsh
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt.Profile -Force -Scope CurrentUser -AllowClobber
          Install-Module -Name MicrosoftPowerBIMgmt.Reports -Force -Scope CurrentUser -AllowClobber
          Import-Module MicrosoftPowerBIMgmt.Profile
          Import-Module MicrosoftPowerBIMgmt.Reports

      - name: Deploy PBIX with PSCredential
        shell: pwsh
        env:
          #AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          #AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          #AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_CLIENT_ID: "c6c3396c-4607-4265-a86b-a06414a655b4"
          AZURE_TENANT_ID: "194b3c5c-48e6-4a3d-959d-d4d84e303fd7"
          AZURE_CLIENT_SECRET: "CNE8Q~8BwoWFBOP7ONngTYXUM8dqI5dUcOYO5bM_"
          
        run: |
          $workspaceId = [Guid]"bf4236fe-57b8-4552-a1a4-e0453da8cb45"
          $pbixPath = "./pbix/Adventure Works DW 2025.pbix"
          $reportName = "Adventure Works DW 2025"

          $secPassword = ConvertTo-SecureString $env:AZURE_CLIENT_SECRET -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential($env:AZURE_CLIENT_ID, $secPassword)

          Connect-PowerBIServiceAccount -Tenant $env:AZURE_TENANT_ID -ServicePrincipal -Credential $credential

          New-PowerBIReport -Path $pbixPath -Name $reportName -WorkspaceId $workspaceId -ConflictAction CreateOrOverwrite
