
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   deploy-powerbi:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Power BI PowerShell module
        shell: pwsh
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt.Profile -Force -Scope CurrentUser -AllowClobber
          Import-Module MicrosoftPowerBIMgmt.Profile

      - name: Run PowerShell deployment script
        shell: pwsh   # use PowerShell Core

        env:
          AZURE_CLIENT_ID: "c6c3396c-4607-4265-a86b-a06414a655b4"
          AZURE_TENANT_ID: "194b3c5c-48e6-4a3d-959d-d4d84e303fd7"
          AZURE_CLIENT_SECRET: "CNE8Q~8BwoWFBOP7ONngTYXUM8dqI5dUcOYO5bM_"
        run: |
          $workspaceId = "bf4236fe-57b8-4552-a1a4-e0453da8cb4"
          $pbixPath = "./pbix/Adventure Works DW 2025.pbix"
          $reportName = "Adventure Works DW 2025"

          Connect-PowerBIServiceAccount `
                      -Tenant $env:AZURE_TENANT_ID `
                      -ClientId $env:AZURE_CLIENT_ID `
                      -ClientSecret $env:AZURE_CLIENT_SECRET

          New-PowerBIReport -Path $pbixPath -Name $reportName -WorkspaceId $workspaceId
